from numpy import ndarray
from typing import Tuple

FULL_BORDER_RADIUS: int

def corner(width: int) -> ndarray:...
def border_alphas_rect(rect_alphas: ndarray, **kwargs) -> None:...
def sub_alphas(background: ndarray, icon: ndarray, topleft: Tuple[int, int]) -> None:...
def reflective(screen_alphas: ndarray, exp: int) -> None:...

class CircleGaussian:
    _center_value: float
    _sigma: float

    def __init__(self, center_value: float, radius: float, radius_value: float) -> None:...
    def gaussian(self, x: float) -> int:...

def corner_gaussian(width: int, center_value: int) -> ndarray:...
def gaussian_circle_alpha(circle: ndarray, center_value: int) -> None:...