from typing import *

def relative_compare(a: float, b: float) -> bool:...
def angle(vec_x: float, vec_y: float) -> float:...
def vector(degrees: float) -> Tuple[int, int]:...
def distance(a_x: float, a_y: float, b_x: float, b_y: float) -> float:...
def lerp(current: float, target: float, delta: float) -> float:...
